// Code generated by protoc-gen-go-template. DO NOT EDIT.
// Source: config.proto

package conf

import "github.com/mogebingxue/game_config_manager"

// 测试子结构
type TestSubStruct struct {
	TestInt    int32  `yaml:"testInt"`    // 测试整型
	TestString string `yaml:"testString"` // 测试字符串
	TestBool   bool   `yaml:"testBool"`   // 测试布尔值
}

// 测试结构
type TestStruct struct {
	TestSubStruct *TestSubStruct `yaml:"testSubStruct"` // 测试子结构
}

// 测试表（单条记录结构）
type TestTable struct {
	TestInt    int32              `yaml:"testInt"`                  // 测试整型
	TestString string             `yaml:"testString"`               // 测试字符串
	TestBool   bool               `yaml:"testBool"`                 // 测试布尔值
	TestEnum   TestEnum           `yaml:"testEnum"`                 // 测试枚举
	TestList   []TestEnum         `yaml:"testList,omitempty"`       // 测试列表（枚举类型）
	TestMap    map[int32]TestEnum `yaml:"testMap,omitempty,inline"` // 测试哈希表（key为int, value为枚举）
	TestStruct *TestStruct        `yaml:"testStruct"`               // 测试结构
}

var testTable *TestTable
var reloadTestTable *TestTable

func (cfg *TestTable) GetFileName() string {
	return "conf/TestTable.json"
}

func (cfg *TestTable) GetResult() interface{} {
	return testTable
}

func (cfg *TestTable) GetReloadResult(alloc bool) interface{} {
	if alloc || reloadTestTable == nil {
		reloadTestTable = new(TestTable)
	}
	return reloadTestTable
}

func (cfg *TestTable) OnReloadFinished() {
	testTable = reloadTestTable
}

func GetTestTable() *TestTable {
	if testTable == nil {
		testTable = &TestTable{}
		config.GetConfigManager().LoadFile(testTable)
	}
	if config.GetConfigManager().IsDirty(testTable.GetFileName()) {
		config.GetConfigManager().ReloadFile(testTable)
	}
	return testTable
}

// 测试枚举
type TestEnum int32

const (
	TestEnum_TEST_ENUM_A TestEnum = 0
	TestEnum_TEST_ENUM_B TestEnum = 1
	TestEnum_TEST_ENUM_C TestEnum = 2
)
